# -*- coding: utf-8 -*-
"""attention mechanism.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18AJep9HyFj-wJsNjGvUTZAXiSxQ0z2XR
"""

#Keep epochs same for all types of models
from tensorflow.keras.layers import Conv2D, Dense, Flatten, AveragePooling2D, GlobalMaxPooling2D,MaxPooling2D,Dropout, BatchNormalization,Activation,GlobalAveragePooling2D
from keras.models import load_model
from tensorflow.keras.layers import Input, Conv2D, BatchNormalization, Activation, MaxPooling2D, Flatten, Dense, Multiply, concatenate
pool_size=(2,2)

x11=base_model.output
#channel attention map
c1=GlobalMaxPooling2D()(x11)
c2=GlobalAveragePooling2D()(x11)
c3=concatenate([c1,c2],axis=1)

c4 = Flatten()(c3)
c5 = Dense(512, activation="softmax")(c4)
c6=tf.keras.layers.Multiply()([c5,x11])

#spatial attention map

s1=AveragePooling2D(pool_size=pool_size, strides=(1, 1),padding='same')(x11)
s2=MaxPooling2D(strides=(1, 1),padding='same')(x11)
#s3=tf.concat([s1,s2],axis=3)
#s3=BatchNormalization()(s3)
#x11=Conv2D(1,(1,1))(x11)

s3=concatenate([s1,s2],axis=3)
s3=BatchNormalization()(s3)
s3=Conv2D(1,(1,1))(s3)
s4 = Flatten()(s3)
s5=Dense(512, activation='relu')(s4)
s6=tf.keras.layers.Multiply()([x11,s5])

#classifier
cl1=tf.keras.layers.Add()([c6,s6])
cl2=BatchNormalization()(cl1)
#cl3=MaxPooling2D()(cl2)
x12=Conv2D(1,(1,1),padding='same',activation='relu')(cl2)

x22=Flatten()(x12)

x23 = Dense(25, activation='relu')(x22)

predictions = Dense(2, activation="softmax")(x23) # Sigmoid for single output neuron

# Create the final model
model19 = Model(inputs=base_model.input, outputs=predictions)
# Compile the model (Our model name is "model19")
model19.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
out1=model19.fit(train_generator, epochs=10, validation_data=test_generator)

test_loss, test_acc = model19.evaluate(test_generator)
print("\nTest Accuracy:", test_acc)


#CONFUSION MATRIX

test_generator.reset()
pred_probs = model19.predict(test_generator)

pred_labels = np.argmax(pred_probs, axis=1)

true_labels = test_generator.classes

cm = confusion_matrix(true_labels, pred_labels)

print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n")
# Make sure target_names match the number of classes in true_labels and pred_labels
print(classification_report(true_labels, pred_labels, target_names=list(test_generator.class_indices.keys())))

plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt="d",
xticklabels=test_generator.class_indices.keys(),
yticklabels=test_generator.class_indices.keys(),
 cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

# ROC CURVE
fpr, tpr, thresholds = roc_curve(true_labels, pred_probs[:, 1])
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.4f}")
plt.plot([0,1], [0,1], linestyle='--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

print("AUC Score:", roc_auc)