# -*- coding: utf-8 -*-
"""fixed_point_representation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18AJep9HyFj-wJsNjGvUTZAXiSxQ0z2XR
"""

import pandas as pd
import math

input_file = "Dense25_Weights_pruned.xlsx"
sheet_name = 0

df = pd.read_excel(input_file, sheet_name=sheet_name)

print("Loaded shape:", df.shape)


# FIXED FORMAT PARAMETERS

INTEGER_BITS = 2
FRACTIONAL_BITS = 5
MAX_INTEGER = 2**INTEGER_BITS - 1  # 3
MIN_INTEGER = - (2**INTEGER_BITS) # -4

#MANUAL Q2.5 CONVERSION
def float_to_manual_q2_5(value):

    # SIGN BIT
    if value < 0:
        sign_bit = '1'
    else:
        sign_bit = '0'

    abs_value = abs(value)

    # INTEGER PART
    integer_part = int(abs_value)

    #Clip integer overflow
    if integer_part > MAX_INTEGER:
        integer_part = MAX_INTEGER

    integer_binary = format(integer_part, '02b')

    #FRACTIONAL PART
    fractional_part = abs_value - integer_part
    fractional_bits = ""

    for _ in range(FRACTIONAL_BITS):
        fractional_part *= 2
        bit = int(fractional_part)
        fractional_bits += str(bit)
        fractional_part -= bit

    #COMBINE
    binary = sign_bit + integer_binary + fractional_bits

    return binary


#APPLY COLUMN-WISE
df_binary = df.copy()

for col in df_binary.columns:
    df_binary[col] = df_binary[col].apply(float_to_manual_q2_5)

output_file = "Dense25_Weights_Q2_5_manual_binary.xlsx"
df_binary.to_excel(output_file, index=False)

print("Manual Q2.5 binary file saved as:", output_file)