# -*- coding: utf-8 -*-
"""model_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18AJep9HyFj-wJsNjGvUTZAXiSxQ0z2XR
"""

base_model.trainable = False # Freeze base layers

x = base_model.output
x = Flatten()(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.5)(x)
output = Dense(2, activation='softmax')(x)

model = Model(inputs=base_model.input, outputs=output)

model.compile(
optimizer=Adam(learning_rate=1e-3),
loss='categorical_crossentropy',
metrics=['categorical_accuracy']
)

model.summary()

# TRAIN MODEL
history = model.fit(
train_generator,
epochs=10,
validation_data=test_generator
)

# EVALUATION
test_loss, test_acc = model.evaluate(test_generator)
print("\nTest Accuracy:", test_acc)