# -*- coding: utf-8 -*-
"""pretrained_cnn_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18AJep9HyFj-wJsNjGvUTZAXiSxQ0z2XR
"""

# 1. IMPORT LIBRARIES
import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import VGG16
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Flatten, Dropout
from tensorflow.keras.optimizers import Adam

from sklearn.metrics import confusion_matrix, classification_report, roc_curve, auc

# 2. PATHS
train_dir = "/content/drive/MyDrive/MedNode_train"
test_dir = "/content/drive/MyDrive/MedNode_test"

IMG_SIZE = 224
BATCH_SIZE = 32

# 3. DATA GENERATORS
train_datagen = ImageDataGenerator(
rescale=1./255,
rotation_range=20,
zoom_range=0.2,
horizontal_flip=True
)
test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
train_dir,
target_size=(IMG_SIZE, IMG_SIZE),
batch_size=BATCH_SIZE,
class_mode='categorical',
shuffle=True)
test_generator = test_datagen.flow_from_directory(
test_dir,
target_size=(IMG_SIZE, IMG_SIZE),
batch_size=BATCH_SIZE,
class_mode='categorical',
shuffle=False
)

# 4. LOAD PRETRAINED VGG16 MODEL
base_model = VGG16(
weights='imagenet',
include_top=False,
input_shape=(IMG_SIZE, IMG_SIZE, 3)
)

