# -*- coding: utf-8 -*-
"""save_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18AJep9HyFj-wJsNjGvUTZAXiSxQ0z2XR
"""

#Save model made for later uses
import numpy as np
import pandas as pd
from openpyxl import Workbook
model19.save("model19.h5")

#LOAD MODEL

model19 = load_model("model19.h5")


# EXTRACT DENSE(25) AND DENSE(2) LAYERS


# Identify Dense layers by units
dense_25_layer = None
dense_2_layer = None

for layer in model19.layers:
    if isinstance(layer, tf.keras.layers.Dense):
       if layer.units == 25:
            dense_25_layer = layer
       elif layer.units == 2:
            dense_2_layer = layer



# GET WEIGHTS AND BIASES

# Dense(25)
w25, b25 = dense_25_layer.get_weights()

# Dense(2)
w2, b2 = dense_2_layer.get_weights()

print("Dense(25) Weights Shape:", w25.shape)
print("Dense(25) Bias Shape:", b25.shape)

print("Dense(2) Weights Shape:", w2.shape)
print("Dense(2) Bias Shape:", b2.shape)

# SAVE TO EXCEL FILE


excel_file = "model19_classifier_weights.xlsx"

with pd.ExcelWriter(excel_file, engine='openpyxl') as writer:

# Dense(25)
    pd.DataFrame(w25).to_excel(writer, sheet_name="Dense25_Weights", index=False)
    pd.DataFrame(b25.reshape(1,-1)).to_excel(writer, sheet_name="Dense25_Bias", index=False)
# Dense(2)
    pd.DataFrame(w2).to_excel(writer, sheet_name="Dense2_Weights", index=False)
    pd.DataFrame(b2.reshape(1,-1)).to_excel(writer, sheet_name="Dense2_Bias", index=False)

print("Excel file saved as:", excel_file)