# -*- coding: utf-8 -*-
"""weight_sharing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18AJep9HyFj-wJsNjGvUTZAXiSxQ0z2XR
"""

import pandas as pd

# LOAD PRUNED EXCEL FILE

input_file = "/content/Dense25_Weights_pruned.xlsx"
sheet_name = 0  # first sheet (or give sheet name)

df = pd.read_excel(input_file, sheet_name=sheet_name)

print("Loaded shape:", df.shape)

# 3. FIND REPEATED VALUES COLUMN-WISE
duplicate_locations = {}

for col in df.columns:

    column_data = df[col]

    # Group by value
    grouped = column_data.groupby(column_data)

    col_duplicates = {}

    for value, indices in grouped.groups.items():

        if len(indices) > 1:  # only repeated values
            col_duplicates[value] = list(indices)

    if col_duplicates:
        duplicate_locations[col] = col_duplicates


# PRINT RESULTS

for col, values in duplicate_locations.items():
    print("\n===================================")
    print("Column:", col)

    for value, rows in values.items():
        print(f"Value {value} found at rows: {rows}")