# -*- coding: utf-8 -*-
"""weight_pruning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18AJep9HyFj-wJsNjGvUTZAXiSxQ0z2XR
"""

#Visualising result for pruning
dense_layers = [layer for layer in model.layers
                if isinstance(layer, tf.keras.layers.Dense)]

if len(dense_layers) < 2:
    print("Model has less than two Dense layers.")
else:
    # Select last two Dense layers
    layers_to_plot = dense_layers[-2:]


    # PLOT HISTOGRAMS

    for layer in layers_to_plot:

        weights, biases = layer.get_weights()

        weights_flat = weights.flatten()
        biases_flat = biases.flatten()


        print("Layer Name:", layer.name)
        print("Units:", layer.units)
        print("Weights Shape:", weights.shape)
        print("Bias Shape:", biases.shape)

        # Weight Histogram
        plt.figure()
        plt.hist(weights_flat, bins=50)
        plt.title(f"{layer.name} - Weights Histogram")
        plt.xlabel("Weight Value")
        plt.ylabel("Frequency")
        plt.grid(True)
        plt.show()

        # Bias Histogram
        plt.figure()
        plt.hist(biases_flat, bins=30)
        plt.title(f"{layer.name} - Bias Histogram")
        plt.xlabel("Bias Value")
        plt.ylabel("Frequency")
        plt.grid(True)
        plt.show()

import pandas as pd
import numpy as np


# LOAD EXCEL FILE

input_file = "model19_classifier_weights.xlsx"
sheet_name = "Dense25_Weights"

df = pd.read_excel(input_file, sheet_name=sheet_name)

print("Original Shape:", df.shape)

# Convert entire dataframe to numeric
df = df.apply(pd.to_numeric)

# COLUMN-WISE PRUNING (ALL ROWS)

for col in df.columns:

    column_data = df[col]

    # Masks
    negative_mask = column_data < -0.1
    positive_mask = column_data > 0.1
    small_mask = (column_data >= -0.1) & (column_data <= 0.1)

    # Compute means column-wise
    neg_mean = column_data[negative_mask].mean() if negative_mask.sum() > 0 else 0
    pos_mean = column_data[positive_mask].mean() if positive_mask.sum() > 0 else 0

    # Apply pruning
    df.loc[small_mask, col] = 0
    df.loc[negative_mask, col] = neg_mean
    df.loc[positive_mask, col] = pos_mean

# SAVE PRUNED FILE
output_file = "Dense25_Weights_pruned.xlsx"
df.to_excel(output_file, index=False)

print("Pruned file saved as:", output_file)